/**
 * DS Accordion — PatternFly 6 Accordion under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Accordion is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Accordion as PFAccordion } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type AccordionProps = ComponentPropsWithoutRef<typeof PFAccordion>;

export function Accordion(props: AccordionProps) {
  return <PFAccordion {...props} />;
}

export {
  AccordionContent,
  AccordionItem,
  AccordionToggle,
} from "@patternfly/react-core";
