/**
 * DS Brand — PatternFly 6 Brand under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Brand is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Brand as PFBrand } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type BrandProps = ComponentPropsWithoutRef<typeof PFBrand>;

export function Brand(props: BrandProps) {
  return <PFBrand {...props} />;
}
