/**
 * DS Button — PatternFly 6 Button under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Button (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Button as PFButton } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type ButtonProps = ComponentPropsWithoutRef<typeof PFButton>;

export const Button: ForwardRefExoticComponent<
  ButtonProps & RefAttributes<ComponentRef<typeof PFButton>>
> = forwardRef<ComponentRef<typeof PFButton>, ButtonProps>(
  function Button(props, ref) {
    return <PFButton ref={ref} {...props} />;
  },
);

export {
  ButtonVariant,
} from "@patternfly/react-core";
