/**
 * DS Card — PatternFly 6 Card under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Card (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Card as PFCard } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type CardProps = ComponentPropsWithoutRef<typeof PFCard>;

export const Card: ForwardRefExoticComponent<
  CardProps & RefAttributes<ComponentRef<typeof PFCard>>
> = forwardRef<ComponentRef<typeof PFCard>, CardProps>(
  function Card(props, ref) {
    return <PFCard ref={ref} {...props} />;
  },
);

export {
  CardBody,
  CardExpandableContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@patternfly/react-core";
