/**
 * DS Checkbox — PatternFly 6 Checkbox under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Checkbox is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Checkbox as PFCheckbox } from "@patternfly/react-core";
import type { CheckboxProps as PFCheckboxProps } from "@patternfly/react-core";

export type CheckboxProps = Omit<PFCheckboxProps, "ref">;

export function Checkbox(props: CheckboxProps) {
  return <PFCheckbox {...props} />;
}
