/**
 * DS ClipboardCopy — PatternFly 6 ClipboardCopy under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's ClipboardCopy is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ClipboardCopy as PFClipboardCopy } from "@patternfly/react-core";
import type { ClipboardCopyProps as PFClipboardCopyProps } from "@patternfly/react-core";

export type ClipboardCopyProps = Omit<PFClipboardCopyProps, "ref">;

export function ClipboardCopy(props: ClipboardCopyProps) {
  return <PFClipboardCopy {...props} />;
}

export {
  ClipboardCopyButton,
  ClipboardCopyVariant,
} from "@patternfly/react-core";
