/**
 * DS CodeBlock — PatternFly 6 CodeBlock under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's CodeBlock is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { CodeBlock as PFCodeBlock } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type CodeBlockProps = ComponentPropsWithoutRef<typeof PFCodeBlock>;

export function CodeBlock(props: CodeBlockProps) {
  return <PFCodeBlock {...props} />;
}

export {
  CodeBlockAction,
  CodeBlockCode,
} from "@patternfly/react-core";
