/**
 * DS Content — PatternFly 6 Content under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Content is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Content as PFContent } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type ContentProps = ComponentPropsWithoutRef<typeof PFContent>;

export function Content(props: ContentProps) {
  return <PFContent {...props} />;
}

export {
  ContentVariants,
} from "@patternfly/react-core";
