/**
 * DS DatePicker — PatternFly 6 DatePicker under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's DatePicker (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { DatePicker as PFDatePicker } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type DatePickerProps = ComponentPropsWithoutRef<typeof PFDatePicker>;

export const DatePicker: ForwardRefExoticComponent<
  DatePickerProps & RefAttributes<ComponentRef<typeof PFDatePicker>>
> = forwardRef<ComponentRef<typeof PFDatePicker>, DatePickerProps>(
  function DatePicker(props, ref) {
    return <PFDatePicker ref={ref} {...props} />;
  },
);
