/**
 * DS Dropdown — PatternFly 6 Dropdown under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Dropdown (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Dropdown as PFDropdown } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type DropdownProps = ComponentPropsWithoutRef<typeof PFDropdown>;

export const Dropdown: ForwardRefExoticComponent<
  DropdownProps & RefAttributes<ComponentRef<typeof PFDropdown>>
> = forwardRef<ComponentRef<typeof PFDropdown>, DropdownProps>(
  function Dropdown(props, ref) {
    return <PFDropdown ref={ref} {...props} />;
  },
);

export {
  DropdownGroup,
  DropdownItem,
  DropdownList,
} from "@patternfly/react-core";
