/**
 * DS Flex — PatternFly 6 Flex under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Flex is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Flex as PFFlex } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type FlexProps = ComponentPropsWithoutRef<typeof PFFlex>;

export function Flex(props: FlexProps) {
  return <PFFlex {...props} />;
}

export {
  FlexItem,
} from "@patternfly/react-core";
