/**
 * DS Form — PatternFly 6 Form under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Form (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Form as PFForm } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type FormProps = ComponentPropsWithoutRef<typeof PFForm>;

export const Form: ForwardRefExoticComponent<
  FormProps & RefAttributes<ComponentRef<typeof PFForm>>
> = forwardRef<ComponentRef<typeof PFForm>, FormProps>(
  function Form(props, ref) {
    return <PFForm ref={ref} {...props} />;
  },
);

export {
  ActionGroup,
  FormGroup,
  FormGroupLabelHelp,
  FormHelperText,
  FormSection,
} from "@patternfly/react-core";
