/**
 * DS FormSelect — PatternFly 6 FormSelect under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's FormSelect is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { FormSelect as PFFormSelect } from "@patternfly/react-core";
import type { FormSelectProps as PFFormSelectProps } from "@patternfly/react-core";

export type FormSelectProps = Omit<PFFormSelectProps, "ref">;

export function FormSelect(props: FormSelectProps) {
  return <PFFormSelect {...props} />;
}

export {
  FormSelectOption,
} from "@patternfly/react-core";
