/**
 * DS Gallery — PatternFly 6 Gallery under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Gallery is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Gallery as PFGallery } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type GalleryProps = ComponentPropsWithoutRef<typeof PFGallery>;

export function Gallery(props: GalleryProps) {
  return <PFGallery {...props} />;
}

export {
  GalleryItem,
} from "@patternfly/react-core";
