/**
 * DS Hint — PatternFly 6 Hint under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Hint is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Hint as PFHint } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type HintProps = ComponentPropsWithoutRef<typeof PFHint>;

export function Hint(props: HintProps) {
  return <PFHint {...props} />;
}

export {
  HintBody,
  HintFooter,
  HintTitle,
} from "@patternfly/react-core";
