/**
 * DS InputGroup — PatternFly 6 InputGroup under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's InputGroup (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { InputGroup as PFInputGroup } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type InputGroupProps = ComponentPropsWithoutRef<typeof PFInputGroup>;

export const InputGroup: ForwardRefExoticComponent<
  InputGroupProps & RefAttributes<ComponentRef<typeof PFInputGroup>>
> = forwardRef<ComponentRef<typeof PFInputGroup>, InputGroupProps>(
  function InputGroup(props, ref) {
    return <PFInputGroup ref={ref} {...props} />;
  },
);

export {
  InputGroupItem,
  InputGroupText,
} from "@patternfly/react-core";
