/**
 * DS JumpLinks — PatternFly 6 JumpLinks under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's JumpLinks is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { JumpLinks as PFJumpLinks } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type JumpLinksProps = ComponentPropsWithoutRef<typeof PFJumpLinks>;

export function JumpLinks(props: JumpLinksProps) {
  return <PFJumpLinks {...props} />;
}

export {
  JumpLinksItem,
  JumpLinksList,
} from "@patternfly/react-core";
