/**
 * DS Level — PatternFly 6 Level under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Level is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Level as PFLevel } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type LevelProps = ComponentPropsWithoutRef<typeof PFLevel>;

export function Level(props: LevelProps) {
  return <PFLevel {...props} />;
}

export {
  LevelItem,
} from "@patternfly/react-core";
