/**
 * DS List — PatternFly 6 List under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's List is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { List as PFList } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type ListProps = ComponentPropsWithoutRef<typeof PFList>;

export function List(props: ListProps) {
  return <PFList {...props} />;
}

export {
  ListComponent,
  ListItem,
  ListVariant,
  OrderType,
} from "@patternfly/react-core";
