/**
 * DS Menu — PatternFly 6 Menu under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Menu (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Menu as PFMenu } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type MenuProps = ComponentPropsWithoutRef<typeof PFMenu>;

export const Menu: ForwardRefExoticComponent<
  MenuProps & RefAttributes<ComponentRef<typeof PFMenu>>
> = forwardRef<ComponentRef<typeof PFMenu>, MenuProps>(
  function Menu(props, ref) {
    return <PFMenu ref={ref} {...props} />;
  },
);

export {
  MenuContent,
  MenuFooter,
  MenuGroup,
  MenuItem,
  MenuItemAction,
  MenuList,
  MenuSearch,
  MenuSearchInput,
} from "@patternfly/react-core";
