/**
 * DS Modal — PatternFly 6 Modal under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Modal is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Modal as PFModal } from "@patternfly/react-core";
import type { ModalProps as PFModalProps } from "@patternfly/react-core";

export type ModalProps = Omit<PFModalProps, "ref">;

export function Modal(props: ModalProps) {
  return <PFModal {...props} />;
}

export {
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalVariant,
} from "@patternfly/react-core";
