/**
 * DS MultipleFileUpload — PatternFly 6 MultipleFileUpload under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's MultipleFileUpload is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { MultipleFileUpload as PFMultipleFileUpload } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type MultipleFileUploadProps = ComponentPropsWithoutRef<typeof PFMultipleFileUpload>;

export function MultipleFileUpload(props: MultipleFileUploadProps) {
  return <PFMultipleFileUpload {...props} />;
}

export {
  MultipleFileUploadMain,
  MultipleFileUploadStatus,
  MultipleFileUploadStatusItem,
} from "@patternfly/react-core";
