/**
 * DS Nav — PatternFly 6 Nav under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Nav is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Nav as PFNav } from "@patternfly/react-core";
import type { NavProps as PFNavProps } from "@patternfly/react-core";

export type NavProps = Omit<PFNavProps, "ref">;

export function Nav(props: NavProps) {
  return <PFNav {...props} />;
}

export {
  NavExpandable,
  NavGroup,
  NavItem,
  NavList,
} from "@patternfly/react-core";
