/**
 * DS NumberInput — PatternFly 6 NumberInput under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's NumberInput is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { NumberInput as PFNumberInput } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type NumberInputProps = ComponentPropsWithoutRef<typeof PFNumberInput>;

export function NumberInput(props: NumberInputProps) {
  return <PFNumberInput {...props} />;
}
