/**
 * DS Panel — PatternFly 6 Panel under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Panel (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Panel as PFPanel } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type PanelProps = ComponentPropsWithoutRef<typeof PFPanel>;

export const Panel: ForwardRefExoticComponent<
  PanelProps & RefAttributes<ComponentRef<typeof PFPanel>>
> = forwardRef<ComponentRef<typeof PFPanel>, PanelProps>(
  function Panel(props, ref) {
    return <PFPanel ref={ref} {...props} />;
  },
);

export {
  PanelFooter,
  PanelHeader,
  PanelMain,
  PanelMainBody,
} from "@patternfly/react-core";
