/**
 * DS Radio — PatternFly 6 Radio under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Radio is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Radio as PFRadio } from "@patternfly/react-core";
import type { RadioProps as PFRadioProps } from "@patternfly/react-core";

export type RadioProps = Omit<PFRadioProps, "ref">;

export function Radio(props: RadioProps) {
  return <PFRadio {...props} />;
}
