/**
 * DS SimpleList — PatternFly 6 SimpleList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's SimpleList is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { SimpleList as PFSimpleList } from "@patternfly/react-core";
import type { SimpleListProps as PFSimpleListProps } from "@patternfly/react-core";

export type SimpleListProps = Omit<PFSimpleListProps, "ref">;

export function SimpleList(props: SimpleListProps) {
  return <PFSimpleList {...props} />;
}

export {
  SimpleListGroup,
  SimpleListItem,
} from "@patternfly/react-core";
