/**
 * DS Split — PatternFly 6 Split under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Split is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Split as PFSplit } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type SplitProps = ComponentPropsWithoutRef<typeof PFSplit>;

export function Split(props: SplitProps) {
  return <PFSplit {...props} />;
}

export {
  SplitItem,
} from "@patternfly/react-core";
