/**
 * DS Stack — PatternFly 6 Stack under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Stack is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Stack as PFStack } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type StackProps = ComponentPropsWithoutRef<typeof PFStack>;

export function Stack(props: StackProps) {
  return <PFStack {...props} />;
}

export {
  StackItem,
} from "@patternfly/react-core";
