/**
 * DS Table — PatternFly 6 Table under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Table (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Table as PFTable } from "@patternfly/react-table";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type TableProps = ComponentPropsWithoutRef<typeof PFTable>;

export const Table: ForwardRefExoticComponent<
  TableProps & RefAttributes<ComponentRef<typeof PFTable>>
> = forwardRef<ComponentRef<typeof PFTable>, TableProps>(
  function Table(props, ref) {
    return <PFTable ref={ref} {...props} />;
  },
);

export {
  ActionsColumn,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@patternfly/react-table";

export type {
  ISortBy,
} from "@patternfly/react-table";
