/**
 * DS Tabs — PatternFly 6 Tabs under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Tabs is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Tabs as PFTabs } from "@patternfly/react-core";
import type { TabsProps as PFTabsProps } from "@patternfly/react-core";

export type TabsProps = Omit<PFTabsProps, "ref">;

export function Tabs(props: TabsProps) {
  return <PFTabs {...props} />;
}

export {
  Tab,
  TabAction,
  TabContent,
  TabContentBody,
  TabTitleIcon,
  TabTitleText,
  TabsComponent,
} from "@patternfly/react-core";
