/**
 * DS TimePicker — PatternFly 6 TimePicker under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's TimePicker is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { TimePicker as PFTimePicker } from "@patternfly/react-core";
import type { TimePickerProps as PFTimePickerProps } from "@patternfly/react-core";

export type TimePickerProps = Omit<PFTimePickerProps, "ref">;

export function TimePicker(props: TimePickerProps) {
  return <PFTimePicker {...props} />;
}
