/**
 * DS Title — PatternFly 6 Title under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Title is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Title as PFTitle } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type TitleProps = ComponentPropsWithoutRef<typeof PFTitle>;

export function Title(props: TitleProps) {
  return <PFTitle {...props} />;
}
