/**
 * DS ToggleGroup — PatternFly 6 ToggleGroup under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's ToggleGroup is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ToggleGroup as PFToggleGroup } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type ToggleGroupProps = ComponentPropsWithoutRef<typeof PFToggleGroup>;

export function ToggleGroup(props: ToggleGroupProps) {
  return <PFToggleGroup {...props} />;
}

export {
  ToggleGroupItem,
} from "@patternfly/react-core";
