/**
 * DS TreeView — PatternFly 6 TreeView under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's TreeView is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { TreeView as PFTreeView } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type TreeViewProps = ComponentPropsWithoutRef<typeof PFTreeView>;

export function TreeView(props: TreeViewProps) {
  return <PFTreeView {...props} />;
}

export type {
  TreeViewDataItem,
} from "@patternfly/react-core";
