/**
 * DS Truncate — PatternFly 6 Truncate under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Truncate (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Truncate as PFTruncate } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type TruncateProps = ComponentPropsWithoutRef<typeof PFTruncate>;

export const Truncate: ForwardRefExoticComponent<
  TruncateProps & RefAttributes<ComponentRef<typeof PFTruncate>>
> = forwardRef<ComponentRef<typeof PFTruncate>, TruncateProps>(
  function Truncate(props, ref) {
    return <PFTruncate ref={ref} {...props} />;
  },
);

export {
  TruncatePosition,
} from "@patternfly/react-core";
