/**
 * DS ActionList — PatternFly 6 ActionList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's ActionList is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ActionList as PFActionList } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type ActionListProps = ComponentPropsWithoutRef<typeof PFActionList>;

export function ActionList(props: ActionListProps) {
  return <PFActionList {...props} />;
}

export {
  ActionListGroup,
  ActionListItem,
} from "@patternfly/react-core";
