/**
 * DS Alert — PatternFly 6 Alert under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Alert is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Alert as PFAlert } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type AlertProps = ComponentPropsWithoutRef<typeof PFAlert>;

export function Alert(props: AlertProps) {
  return <PFAlert {...props} />;
}

export {
  AlertActionCloseButton,
  AlertActionLink,
  AlertGroup,
  AlertVariant,
} from "@patternfly/react-core";
