/**
 * DS Alert — PatternFly 6 Alert under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Alert as PFAlert } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type AlertProps = Omit<ComponentProps<typeof PFAlert>, "ref">;

export function Alert(props: AlertProps) {
  return <PFAlert {...props} />;
}

export {
  AlertActionCloseButton,
  AlertActionLink,
  AlertGroup,
} from "@patternfly/react-core";
