/**
 * DS Avatar — PatternFly 6 Avatar under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Avatar as PFAvatar } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type AvatarProps = Omit<ComponentProps<typeof PFAvatar>, "ref">;

export function Avatar(props: AvatarProps) {
  return <PFAvatar {...props} />;
}
