/**
 * DS Avatar — PatternFly 6 Avatar under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Avatar is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Avatar as PFAvatar } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type AvatarProps = ComponentPropsWithoutRef<typeof PFAvatar>;

export function Avatar(props: AvatarProps) {
  return <PFAvatar {...props} />;
}
