/**
 * DS BackToTop — PatternFly 6 BackToTop under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { BackToTop as PFBackToTop } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BackToTopProps = Omit<ComponentProps<typeof PFBackToTop>, "ref">;

export function BackToTop(props: BackToTopProps) {
  return <PFBackToTop {...props} />;
}
