/**
 * DS BackToTop — PatternFly 6 BackToTop under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's BackToTop (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { BackToTop as PFBackToTop } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type BackToTopProps = ComponentPropsWithoutRef<typeof PFBackToTop>;

export const BackToTop: ForwardRefExoticComponent<
  BackToTopProps & RefAttributes<ComponentRef<typeof PFBackToTop>>
> = forwardRef<ComponentRef<typeof PFBackToTop>, BackToTopProps>(
  function BackToTop(props, ref) {
    return <PFBackToTop ref={ref} {...props} />;
  },
);
