/**
 * DS Backdrop — PatternFly 6 Backdrop under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Backdrop as PFBackdrop } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BackdropProps = Omit<ComponentProps<typeof PFBackdrop>, "ref">;

export function Backdrop(props: BackdropProps) {
  return <PFBackdrop {...props} />;
}
