/**
 * DS Badge — PatternFly 6 Badge under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Badge is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Badge as PFBadge } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type BadgeProps = ComponentPropsWithoutRef<typeof PFBadge>;

export function Badge(props: BadgeProps) {
  return <PFBadge {...props} />;
}
