/**
 * DS Banner — PatternFly 6 Banner under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Banner is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Banner as PFBanner } from "@patternfly/react-core";
import type { ComponentProps, ComponentPropsWithoutRef } from "react";

export type BannerProps = ComponentPropsWithoutRef<typeof PFBanner>;

export function Banner(props: BannerProps) {
  return <PFBanner {...(props as ComponentProps<typeof PFBanner>)} />;
}
