/**
 * DS Banner — PatternFly 6 Banner under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Banner as PFBanner } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BannerProps = Omit<ComponentProps<typeof PFBanner>, "ref">;

export function Banner(props: BannerProps) {
  // PF types BannerProps as a union (status | non-status banner); spreading
  // a union fights exactOptionalPropertyTypes, so re-assert the PF type.
  return <PFBanner {...(props as ComponentProps<typeof PFBanner>)} />;
}
