/**
 * DS Brand — PatternFly 6 Brand under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Brand as PFBrand } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BrandProps = Omit<ComponentProps<typeof PFBrand>, "ref">;

export function Brand(props: BrandProps) {
  return <PFBrand {...props} />;
}
