/**
 * DS Breadcrumb — PatternFly 6 Breadcrumb under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Breadcrumb as PFBreadcrumb } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BreadcrumbProps = Omit<ComponentProps<typeof PFBreadcrumb>, "ref">;

export function Breadcrumb(props: BreadcrumbProps) {
  return <PFBreadcrumb {...props} />;
}

export {
  BreadcrumbHeading,
  BreadcrumbItem,
} from "@patternfly/react-core";
