/**
 * DS Bullseye — PatternFly 6 Bullseye under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Bullseye is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Bullseye as PFBullseye } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type BullseyeProps = ComponentPropsWithoutRef<typeof PFBullseye>;

export function Bullseye(props: BullseyeProps) {
  return <PFBullseye {...props} />;
}
