/**
 * DS Bullseye — PatternFly 6 Bullseye under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Bullseye as PFBullseye } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type BullseyeProps = Omit<ComponentProps<typeof PFBullseye>, "ref">;

export function Bullseye(props: BullseyeProps) {
  return <PFBullseye {...props} />;
}
