/**
 * DS Button — PatternFly 6 Button under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Button as PFButton } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ButtonProps = Omit<ComponentProps<typeof PFButton>, "ref">;

export function Button(props: ButtonProps) {
  return <PFButton {...props} />;
}

export {
  ButtonVariant,
} from "@patternfly/react-core";
