/**
 * DS CalendarMonth — PatternFly 6 CalendarMonth under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { CalendarMonth as PFCalendarMonth } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type CalendarMonthProps = Omit<ComponentProps<typeof PFCalendarMonth>, "ref">;

export function CalendarMonth(props: CalendarMonthProps) {
  return <PFCalendarMonth {...props} />;
}
