/**
 * DS Card — PatternFly 6 Card under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Card as PFCard } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type CardProps = Omit<ComponentProps<typeof PFCard>, "ref">;

export function Card(props: CardProps) {
  return <PFCard {...props} />;
}

export {
  CardBody,
  CardExpandableContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@patternfly/react-core";
