/**
 * DS Checkbox — PatternFly 6 Checkbox under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Checkbox as PFCheckbox } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type CheckboxProps = Omit<ComponentProps<typeof PFCheckbox>, "ref">;

export function Checkbox(props: CheckboxProps) {
  return <PFCheckbox {...props} />;
}
