/**
 * DS ClipboardCopy — PatternFly 6 ClipboardCopy under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ClipboardCopy as PFClipboardCopy } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ClipboardCopyProps = Omit<ComponentProps<typeof PFClipboardCopy>, "ref">;

export function ClipboardCopy(props: ClipboardCopyProps) {
  return <PFClipboardCopy {...props} />;
}

export {
  ClipboardCopyButton,
  ClipboardCopyVariant,
} from "@patternfly/react-core";
