/**
 * DS CodeBlock — PatternFly 6 CodeBlock under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { CodeBlock as PFCodeBlock } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type CodeBlockProps = Omit<ComponentProps<typeof PFCodeBlock>, "ref">;

export function CodeBlock(props: CodeBlockProps) {
  return <PFCodeBlock {...props} />;
}

export {
  CodeBlockAction,
  CodeBlockCode,
} from "@patternfly/react-core";
