/**
 * DS Compass — PatternFly 6 Compass under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Compass is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Compass as PFCompass } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type CompassProps = ComponentPropsWithoutRef<typeof PFCompass>;

export function Compass(props: CompassProps) {
  return <PFCompass {...props} />;
}

export {
  CompassContent,
  CompassHeader,
  CompassHero,
  CompassMainHeader,
  CompassMainHeaderContent,
  CompassMessageBar,
  CompassNavContent,
  CompassNavHome,
  CompassNavMain,
  CompassNavSearch,
} from "@patternfly/react-core";
