/**
 * DS Content — PatternFly 6 Content under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Content as PFContent } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ContentProps = Omit<ComponentProps<typeof PFContent>, "ref">;

export function Content(props: ContentProps) {
  return <PFContent {...props} />;
}
