/**
 * DS DataList — PatternFly 6 DataList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { DataList as PFDataList } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DataListProps = Omit<ComponentProps<typeof PFDataList>, "ref">;

export function DataList(props: DataListProps) {
  return <PFDataList {...props} />;
}

export {
  DataListAction,
  DataListCell,
  DataListCheck,
  DataListContent,
  DataListItem,
  DataListItemCells,
  DataListItemRow,
  DataListToggle,
} from "@patternfly/react-core";
