/**
 * DS DataList — PatternFly 6 DataList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's DataList (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { DataList as PFDataList } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type DataListProps = ComponentPropsWithoutRef<typeof PFDataList>;

export const DataList: ForwardRefExoticComponent<
  DataListProps & RefAttributes<ComponentRef<typeof PFDataList>>
> = forwardRef<ComponentRef<typeof PFDataList>, DataListProps>(
  function DataList(props, ref) {
    return <PFDataList ref={ref} {...props} />;
  },
);

export {
  DataListAction,
  DataListCell,
  DataListCheck,
  DataListContent,
  DataListItem,
  DataListItemCells,
  DataListItemRow,
  DataListToggle,
} from "@patternfly/react-core";
