/**
 * DS DatePicker — PatternFly 6 DatePicker under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { DatePicker as PFDatePicker } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DatePickerProps = Omit<ComponentProps<typeof PFDatePicker>, "ref">;

export function DatePicker(props: DatePickerProps) {
  return <PFDatePicker {...props} />;
}
