/**
 * DS DescriptionList — PatternFly 6 DescriptionList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { DescriptionList as PFDescriptionList } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DescriptionListProps = Omit<ComponentProps<typeof PFDescriptionList>, "ref">;

export function DescriptionList(props: DescriptionListProps) {
  return <PFDescriptionList {...props} />;
}

export {
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
} from "@patternfly/react-core";
