/**
 * DS Divider — PatternFly 6 Divider under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Divider is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Divider as PFDivider } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type DividerProps = ComponentPropsWithoutRef<typeof PFDivider>;

export function Divider(props: DividerProps) {
  return <PFDivider {...props} />;
}
