/**
 * DS Divider — PatternFly 6 Divider under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Divider as PFDivider } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DividerProps = Omit<ComponentProps<typeof PFDivider>, "ref">;

export function Divider(props: DividerProps) {
  return <PFDivider {...props} />;
}
