/**
 * DS Drawer — PatternFly 6 Drawer under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Drawer is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Drawer as PFDrawer } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type DrawerProps = ComponentPropsWithoutRef<typeof PFDrawer>;

export function Drawer(props: DrawerProps) {
  return <PFDrawer {...props} />;
}

export {
  DrawerActions,
  DrawerCloseButton,
  DrawerContent,
  DrawerContentBody,
  DrawerHead,
  DrawerPanelBody,
  DrawerPanelContent,
  DrawerPanelDescription,
} from "@patternfly/react-core";
