/**
 * DS Dropdown — PatternFly 6 Dropdown under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Dropdown as PFDropdown } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DropdownProps = Omit<ComponentProps<typeof PFDropdown>, "ref">;

export function Dropdown(props: DropdownProps) {
  return <PFDropdown {...props} />;
}

export {
  DropdownGroup,
  DropdownItem,
  DropdownList,
} from "@patternfly/react-core";
