/**
 * DS DualListSelector — PatternFly 6 DualListSelector under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { DualListSelector as PFDualListSelector } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type DualListSelectorProps = Omit<ComponentProps<typeof PFDualListSelector>, "ref">;

export function DualListSelector(props: DualListSelectorProps) {
  return <PFDualListSelector {...props} />;
}

export {
  DualListSelectorControl,
  DualListSelectorControlsWrapper,
  DualListSelectorList,
  DualListSelectorListItem,
  DualListSelectorPane,
} from "@patternfly/react-core";
