/**
 * DS EmptyState — PatternFly 6 EmptyState under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's EmptyState is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { EmptyState as PFEmptyState } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type EmptyStateProps = ComponentPropsWithoutRef<typeof PFEmptyState>;

export function EmptyState(props: EmptyStateProps) {
  return <PFEmptyState {...props} />;
}

export {
  EmptyStateActions,
  EmptyStateBody,
  EmptyStateFooter,
} from "@patternfly/react-core";
