/**
 * DS ExpandableSection — PatternFly 6 ExpandableSection under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's ExpandableSection is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ExpandableSection as PFExpandableSection } from "@patternfly/react-core";
import type { ExpandableSectionProps as PFExpandableSectionProps } from "@patternfly/react-core";

export type ExpandableSectionProps = Omit<PFExpandableSectionProps, "ref">;

export function ExpandableSection(props: ExpandableSectionProps) {
  return <PFExpandableSection {...props} />;
}

export {
  ExpandableSectionToggle,
  ExpandableSectionVariant,
} from "@patternfly/react-core";
