/**
 * DS ExpandableSection — PatternFly 6 ExpandableSection under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ExpandableSection as PFExpandableSection } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ExpandableSectionProps = Omit<ComponentProps<typeof PFExpandableSection>, "ref">;

export function ExpandableSection(props: ExpandableSectionProps) {
  return <PFExpandableSection {...props} />;
}

export {
  ExpandableSectionToggle,
  ExpandableSectionVariant,
} from "@patternfly/react-core";
