/**
 * DS FileUpload — PatternFly 6 FileUpload under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { FileUpload as PFFileUpload } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type FileUploadProps = Omit<ComponentProps<typeof PFFileUpload>, "ref">;

export function FileUpload(props: FileUploadProps) {
  return <PFFileUpload {...props} />;
}
