/**
 * DS Flex — PatternFly 6 Flex under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Flex as PFFlex } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type FlexProps = Omit<ComponentProps<typeof PFFlex>, "ref">;

export function Flex(props: FlexProps) {
  return <PFFlex {...props} />;
}

export {
  FlexItem,
} from "@patternfly/react-core";
