/**
 * DS Form — PatternFly 6 Form under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Form as PFForm } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type FormProps = Omit<ComponentProps<typeof PFForm>, "ref">;

export function Form(props: FormProps) {
  return <PFForm {...props} />;
}

export {
  ActionGroup,
  FormGroup,
  FormGroupLabelHelp,
  FormHelperText,
  FormSection,
} from "@patternfly/react-core";
