/**
 * DS FormSelect — PatternFly 6 FormSelect under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { FormSelect as PFFormSelect } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type FormSelectProps = Omit<ComponentProps<typeof PFFormSelect>, "ref">;

export function FormSelect(props: FormSelectProps) {
  return <PFFormSelect {...props} />;
}

export {
  FormSelectOption,
} from "@patternfly/react-core";
