/**
 * DS Gallery — PatternFly 6 Gallery under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Gallery as PFGallery } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type GalleryProps = Omit<ComponentProps<typeof PFGallery>, "ref">;

export function Gallery(props: GalleryProps) {
  return <PFGallery {...props} />;
}

export {
  GalleryItem,
} from "@patternfly/react-core";
