/**
 * DS Grid — PatternFly 6 Grid under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Grid is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Grid as PFGrid } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type GridProps = ComponentPropsWithoutRef<typeof PFGrid>;

export function Grid(props: GridProps) {
  return <PFGrid {...props} />;
}

export {
  GridItem,
} from "@patternfly/react-core";
