/**
 * DS HelperText — PatternFly 6 HelperText under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { HelperText as PFHelperText } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type HelperTextProps = Omit<ComponentProps<typeof PFHelperText>, "ref">;

export function HelperText(props: HelperTextProps) {
  return <PFHelperText {...props} />;
}

export {
  HelperTextItem,
} from "@patternfly/react-core";
