/**
 * DS HelperText — PatternFly 6 HelperText under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's HelperText is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { HelperText as PFHelperText } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type HelperTextProps = ComponentPropsWithoutRef<typeof PFHelperText>;

export function HelperText(props: HelperTextProps) {
  return <PFHelperText {...props} />;
}

export {
  HelperTextItem,
} from "@patternfly/react-core";
