/**
 * DS Hero — PatternFly 6 Hero under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Hero is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Hero as PFHero } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type HeroProps = ComponentPropsWithoutRef<typeof PFHero>;

export function Hero(props: HeroProps) {
  return <PFHero {...props} />;
}
