/**
 * DS Hero — PatternFly 6 Hero under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Hero as PFHero } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type HeroProps = Omit<ComponentProps<typeof PFHero>, "ref">;

export function Hero(props: HeroProps) {
  return <PFHero {...props} />;
}
