/**
 * DS Icon — PatternFly 6 Icon under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Icon as PFIcon } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type IconProps = Omit<ComponentProps<typeof PFIcon>, "ref">;

export function Icon(props: IconProps) {
  return <PFIcon {...props} />;
}
