/**
 * DS InputGroup — PatternFly 6 InputGroup under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { InputGroup as PFInputGroup } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type InputGroupProps = Omit<ComponentProps<typeof PFInputGroup>, "ref">;

export function InputGroup(props: InputGroupProps) {
  return <PFInputGroup {...props} />;
}

export {
  InputGroupItem,
  InputGroupText,
} from "@patternfly/react-core";
