/**
 * DS JumpLinks — PatternFly 6 JumpLinks under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { JumpLinks as PFJumpLinks } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type JumpLinksProps = Omit<ComponentProps<typeof PFJumpLinks>, "ref">;

export function JumpLinks(props: JumpLinksProps) {
  return <PFJumpLinks {...props} />;
}

export {
  JumpLinksItem,
  JumpLinksList,
} from "@patternfly/react-core";
