/**
 * DS Label — PatternFly 6 Label under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Label is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Label as PFLabel } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type LabelProps = ComponentPropsWithoutRef<typeof PFLabel>;

export function Label(props: LabelProps) {
  return <PFLabel {...props} />;
}

export {
  LabelGroup,
} from "@patternfly/react-core";
