/**
 * DS Label — PatternFly 6 Label under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Label as PFLabel } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type LabelProps = Omit<ComponentProps<typeof PFLabel>, "ref">;

export function Label(props: LabelProps) {
  return <PFLabel {...props} />;
}
