/**
 * DS List — PatternFly 6 List under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { List as PFList } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ListProps = Omit<ComponentProps<typeof PFList>, "ref">;

export function List(props: ListProps) {
  return <PFList {...props} />;
}

export {
  ListComponent,
  ListItem,
  ListVariant,
  OrderType,
} from "@patternfly/react-core";
