/**
 * DS LoginPage — PatternFly 6 LoginPage under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { LoginPage as PFLoginPage } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type LoginPageProps = Omit<ComponentProps<typeof PFLoginPage>, "ref">;

export function LoginPage(props: LoginPageProps) {
  return <PFLoginPage {...props} />;
}

export {
  LoginFooterItem,
  LoginForm,
  LoginMainFooterBandItem,
  LoginMainFooterLinksItem,
} from "@patternfly/react-core";
