/**
 * DS Masthead — PatternFly 6 Masthead under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Masthead as PFMasthead } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type MastheadProps = Omit<ComponentProps<typeof PFMasthead>, "ref">;

export function Masthead(props: MastheadProps) {
  return <PFMasthead {...props} />;
}

export {
  MastheadBrand,
  MastheadContent,
  MastheadLogo,
  MastheadMain,
  MastheadToggle,
} from "@patternfly/react-core";
