/**
 * DS Menu — PatternFly 6 Menu under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Menu as PFMenu } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type MenuProps = Omit<ComponentProps<typeof PFMenu>, "ref">;

export function Menu(props: MenuProps) {
  return <PFMenu {...props} />;
}

export {
  MenuContent,
  MenuFooter,
  MenuGroup,
  MenuItem,
  MenuItemAction,
  MenuList,
  MenuSearch,
  MenuSearchInput,
} from "@patternfly/react-core";
