/**
 * DS MenuToggle — PatternFly 6 MenuToggle under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's MenuToggle (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { MenuToggle as PFMenuToggle } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type MenuToggleProps = ComponentPropsWithoutRef<typeof PFMenuToggle>;

export const MenuToggle: ForwardRefExoticComponent<
  MenuToggleProps & RefAttributes<ComponentRef<typeof PFMenuToggle>>
> = forwardRef<ComponentRef<typeof PFMenuToggle>, MenuToggleProps>(
  function MenuToggle(props, ref) {
    return <PFMenuToggle ref={ref} {...props} />;
  },
);

export {
  MenuToggleAction,
  MenuToggleCheckbox,
} from "@patternfly/react-core";

export type {
  MenuToggleElement,
} from "@patternfly/react-core";
