/**
 * DS Modal — PatternFly 6 Modal under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Modal as PFModal } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ModalProps = Omit<ComponentProps<typeof PFModal>, "ref">;

export function Modal(props: ModalProps) {
  return <PFModal {...props} />;
}

export {
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalVariant,
} from "@patternfly/react-core";
