/**
 * DS MultipleFileUpload — PatternFly 6 MultipleFileUpload under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { MultipleFileUpload as PFMultipleFileUpload } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type MultipleFileUploadProps = Omit<ComponentProps<typeof PFMultipleFileUpload>, "ref">;

export function MultipleFileUpload(props: MultipleFileUploadProps) {
  return <PFMultipleFileUpload {...props} />;
}

export {
  MultipleFileUploadMain,
  MultipleFileUploadStatus,
  MultipleFileUploadStatusItem,
} from "@patternfly/react-core";
