/**
 * DS Nav — PatternFly 6 Nav under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Nav as PFNav } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type NavProps = Omit<ComponentProps<typeof PFNav>, "ref">;

export function Nav(props: NavProps) {
  return <PFNav {...props} />;
}

export {
  NavExpandable,
  NavGroup,
  NavItem,
  NavList,
} from "@patternfly/react-core";
