/**
 * DS NotificationBadge — PatternFly 6 NotificationBadge under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's NotificationBadge is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { NotificationBadge as PFNotificationBadge } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type NotificationBadgeProps = ComponentPropsWithoutRef<typeof PFNotificationBadge>;

export function NotificationBadge(props: NotificationBadgeProps) {
  return <PFNotificationBadge {...props} />;
}

export {
  NotificationBadgeVariant,
} from "@patternfly/react-core";
