/**
 * DS NotificationBadge — PatternFly 6 NotificationBadge under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { NotificationBadge as PFNotificationBadge } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type NotificationBadgeProps = Omit<ComponentProps<typeof PFNotificationBadge>, "ref">;

export function NotificationBadge(props: NotificationBadgeProps) {
  return <PFNotificationBadge {...props} />;
}

export {
  NotificationBadgeVariant,
} from "@patternfly/react-core";
