/**
 * DS NotificationDrawer — PatternFly 6 NotificationDrawer under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's NotificationDrawer (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { NotificationDrawer as PFNotificationDrawer } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type NotificationDrawerProps = ComponentPropsWithoutRef<typeof PFNotificationDrawer>;

export const NotificationDrawer: ForwardRefExoticComponent<
  NotificationDrawerProps & RefAttributes<ComponentRef<typeof PFNotificationDrawer>>
> = forwardRef<ComponentRef<typeof PFNotificationDrawer>, NotificationDrawerProps>(
  function NotificationDrawer(props, ref) {
    return <PFNotificationDrawer ref={ref} {...props} />;
  },
);

export {
  NotificationDrawerBody,
  NotificationDrawerHeader,
  NotificationDrawerList,
  NotificationDrawerListItem,
  NotificationDrawerListItemBody,
  NotificationDrawerListItemHeader,
} from "@patternfly/react-core";
