/**
 * DS NotificationDrawer — PatternFly 6 NotificationDrawer under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { NotificationDrawer as PFNotificationDrawer } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type NotificationDrawerProps = Omit<ComponentProps<typeof PFNotificationDrawer>, "ref">;

export function NotificationDrawer(props: NotificationDrawerProps) {
  return <PFNotificationDrawer {...props} />;
}

export {
  NotificationDrawerBody,
  NotificationDrawerHeader,
  NotificationDrawerList,
  NotificationDrawerListItem,
  NotificationDrawerListItemBody,
  NotificationDrawerListItemHeader,
} from "@patternfly/react-core";
