/**
 * DS NumberInput — PatternFly 6 NumberInput under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { NumberInput as PFNumberInput } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type NumberInputProps = Omit<ComponentProps<typeof PFNumberInput>, "ref">;

export function NumberInput(props: NumberInputProps) {
  return <PFNumberInput {...props} />;
}
