/**
 * DS OverflowMenu — PatternFly 6 OverflowMenu under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's OverflowMenu is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { OverflowMenu as PFOverflowMenu } from "@patternfly/react-core";
import type { OverflowMenuProps as PFOverflowMenuProps } from "@patternfly/react-core";

export type OverflowMenuProps = Omit<PFOverflowMenuProps, "ref">;

export function OverflowMenu(props: OverflowMenuProps) {
  return <PFOverflowMenu {...props} />;
}

export {
  OverflowMenuContent,
  OverflowMenuControl,
  OverflowMenuDropdownItem,
  OverflowMenuGroup,
  OverflowMenuItem,
} from "@patternfly/react-core";
