/**
 * DS OverflowMenu — PatternFly 6 OverflowMenu under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { OverflowMenu as PFOverflowMenu } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type OverflowMenuProps = Omit<ComponentProps<typeof PFOverflowMenu>, "ref">;

export function OverflowMenu(props: OverflowMenuProps) {
  return <PFOverflowMenu {...props} />;
}

export {
  OverflowMenuContent,
  OverflowMenuControl,
  OverflowMenuDropdownItem,
  OverflowMenuGroup,
  OverflowMenuItem,
} from "@patternfly/react-core";
