/**
 * DS Page — PatternFly 6 Page under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Page as PFPage } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type PageProps = Omit<ComponentProps<typeof PFPage>, "ref">;

export function Page(props: PageProps) {
  return <PFPage {...props} />;
}

export {
  PageSection,
  PageSidebar,
  PageSidebarBody,
  PageToggleButton,
} from "@patternfly/react-core";
