/**
 * DS Page — PatternFly 6 Page under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Page is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Page as PFPage } from "@patternfly/react-core";
import type { PageProps as PFPageProps } from "@patternfly/react-core";

export type PageProps = Omit<PFPageProps, "ref">;

export function Page(props: PageProps) {
  return <PFPage {...props} />;
}

export {
  PageSection,
  PageSidebar,
  PageSidebarBody,
  PageToggleButton,
} from "@patternfly/react-core";
