/**
 * DS Pagination — PatternFly 6 Pagination under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Pagination is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Pagination as PFPagination } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type PaginationProps = ComponentPropsWithoutRef<typeof PFPagination>;

export function Pagination(props: PaginationProps) {
  return <PFPagination {...props} />;
}

export {
  PaginationVariant,
} from "@patternfly/react-core";
