/**
 * DS Panel — PatternFly 6 Panel under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Panel as PFPanel } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type PanelProps = Omit<ComponentProps<typeof PFPanel>, "ref">;

export function Panel(props: PanelProps) {
  return <PFPanel {...props} />;
}

export {
  PanelFooter,
  PanelHeader,
  PanelMain,
  PanelMainBody,
} from "@patternfly/react-core";
