/**
 * DS Popover — PatternFly 6 Popover under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Popover as PFPopover } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type PopoverProps = Omit<ComponentProps<typeof PFPopover>, "ref">;

export function Popover(props: PopoverProps) {
  return <PFPopover {...props} />;
}
