/**
 * DS Popover — PatternFly 6 Popover under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Popover is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Popover as PFPopover } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type PopoverProps = ComponentPropsWithoutRef<typeof PFPopover>;

export function Popover(props: PopoverProps) {
  return <PFPopover {...props} />;
}
