/**
 * DS ProgressStepper — PatternFly 6 ProgressStepper under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ProgressStepper as PFProgressStepper } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ProgressStepperProps = Omit<ComponentProps<typeof PFProgressStepper>, "ref">;

export function ProgressStepper(props: ProgressStepperProps) {
  return <PFProgressStepper {...props} />;
}

export {
  ProgressStep,
} from "@patternfly/react-core";
