/**
 * DS Progress — PatternFly 6 Progress under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Progress as PFProgress } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ProgressProps = Omit<ComponentProps<typeof PFProgress>, "ref">;

export function Progress(props: ProgressProps) {
  return <PFProgress {...props} />;
}

export {
  ProgressMeasureLocation,
  ProgressSize,
  ProgressVariant,
} from "@patternfly/react-core";
