/**
 * DS Progress — PatternFly 6 Progress under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Progress is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Progress as PFProgress } from "@patternfly/react-core";
import type { ProgressProps as PFProgressProps } from "@patternfly/react-core";

export type ProgressProps = Omit<PFProgressProps, "ref">;

export function Progress(props: ProgressProps) {
  return <PFProgress {...props} />;
}

export {
  ProgressMeasureLocation,
  ProgressSize,
  ProgressVariant,
} from "@patternfly/react-core";
