/**
 * DS Radio — PatternFly 6 Radio under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Radio as PFRadio } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type RadioProps = Omit<ComponentProps<typeof PFRadio>, "ref">;

export function Radio(props: RadioProps) {
  return <PFRadio {...props} />;
}
