/**
 * DS SearchInput — PatternFly 6 SearchInput under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { SearchInput as PFSearchInput } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SearchInputProps = Omit<ComponentProps<typeof PFSearchInput>, "ref">;

export function SearchInput(props: SearchInputProps) {
  return <PFSearchInput {...props} />;
}
