/**
 * DS SearchInput — PatternFly 6 SearchInput under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's SearchInput (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { SearchInput as PFSearchInput } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type SearchInputProps = ComponentPropsWithoutRef<typeof PFSearchInput>;

export const SearchInput: ForwardRefExoticComponent<
  SearchInputProps & RefAttributes<ComponentRef<typeof PFSearchInput>>
> = forwardRef<ComponentRef<typeof PFSearchInput>, SearchInputProps>(
  function SearchInput(props, ref) {
    return <PFSearchInput ref={ref} {...props} />;
  },
);
