/**
 * DS Select — PatternFly 6 Select under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Select as PFSelect } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SelectProps = Omit<ComponentProps<typeof PFSelect>, "ref">;

export function Select(props: SelectProps) {
  return <PFSelect {...props} />;
}

export {
  SelectGroup,
  SelectList,
  SelectOption,
} from "@patternfly/react-core";
