/**
 * DS Select — PatternFly 6 Select under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's Select (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { Select as PFSelect } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type SelectProps = ComponentPropsWithoutRef<typeof PFSelect>;

export const Select: ForwardRefExoticComponent<
  SelectProps & RefAttributes<ComponentRef<typeof PFSelect>>
> = forwardRef<ComponentRef<typeof PFSelect>, SelectProps>(
  function Select(props, ref) {
    return <PFSelect ref={ref} {...props} />;
  },
);

export {
  SelectGroup,
  SelectList,
  SelectOption,
} from "@patternfly/react-core";

export type {
  SelectOptionProps,
} from "@patternfly/react-core";
