/**
 * DS Sidebar — PatternFly 6 Sidebar under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Sidebar as PFSidebar } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SidebarProps = Omit<ComponentProps<typeof PFSidebar>, "ref">;

export function Sidebar(props: SidebarProps) {
  return <PFSidebar {...props} />;
}

export {
  SidebarContent,
  SidebarPanel,
} from "@patternfly/react-core";
