/**
 * DS SimpleList — PatternFly 6 SimpleList under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { SimpleList as PFSimpleList } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SimpleListProps = Omit<ComponentProps<typeof PFSimpleList>, "ref">;

export function SimpleList(props: SimpleListProps) {
  return <PFSimpleList {...props} />;
}

export {
  SimpleListGroup,
  SimpleListItem,
} from "@patternfly/react-core";
