/**
 * DS Skeleton — PatternFly 6 Skeleton under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Skeleton as PFSkeleton } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SkeletonProps = Omit<ComponentProps<typeof PFSkeleton>, "ref">;

export function Skeleton(props: SkeletonProps) {
  return <PFSkeleton {...props} />;
}
