/**
 * DS Slider — PatternFly 6 Slider under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Slider as PFSlider } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SliderProps = Omit<ComponentProps<typeof PFSlider>, "ref">;

export function Slider(props: SliderProps) {
  return <PFSlider {...props} />;
}
