/**
 * DS Slider — PatternFly 6 Slider under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Slider is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Slider as PFSlider } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type SliderProps = ComponentPropsWithoutRef<typeof PFSlider>;

export function Slider(props: SliderProps) {
  return <PFSlider {...props} />;
}
