/**
 * DS Spinner — PatternFly 6 Spinner under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Spinner as PFSpinner } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SpinnerProps = Omit<ComponentProps<typeof PFSpinner>, "ref">;

export function Spinner(props: SpinnerProps) {
  return <PFSpinner {...props} />;
}
