/**
 * DS Switch — PatternFly 6 Switch under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Switch is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Switch as PFSwitch } from "@patternfly/react-core";
import type { SwitchProps as PFSwitchProps } from "@patternfly/react-core";

export type SwitchProps = Omit<PFSwitchProps, "ref">;

export function Switch(props: SwitchProps) {
  return <PFSwitch {...props} />;
}
