/**
 * DS Switch — PatternFly 6 Switch under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Switch as PFSwitch } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type SwitchProps = Omit<ComponentProps<typeof PFSwitch>, "ref">;

export function Switch(props: SwitchProps) {
  return <PFSwitch {...props} />;
}
