/**
 * DS Tabs — PatternFly 6 Tabs under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Tabs as PFTabs } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TabsProps = Omit<ComponentProps<typeof PFTabs>, "ref">;

export function Tabs(props: TabsProps) {
  return <PFTabs {...props} />;
}

export {
  Tab,
  TabAction,
  TabContent,
  TabContentBody,
  TabTitleIcon,
  TabTitleText,
  TabsComponent,
} from "@patternfly/react-core";
