/**
 * DS TextInputGroup — PatternFly 6 TextInputGroup under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { TextInputGroup as PFTextInputGroup } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TextInputGroupProps = Omit<ComponentProps<typeof PFTextInputGroup>, "ref">;

export function TextInputGroup(props: TextInputGroupProps) {
  return <PFTextInputGroup {...props} />;
}

export {
  TextInputGroupMain,
  TextInputGroupUtilities,
} from "@patternfly/react-core";
