/**
 * DS TextArea — PatternFly 6 TextArea under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's TextArea (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { TextArea as PFTextArea } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type TextAreaProps = ComponentPropsWithoutRef<typeof PFTextArea>;

export const TextArea: ForwardRefExoticComponent<
  TextAreaProps & RefAttributes<ComponentRef<typeof PFTextArea>>
> = forwardRef<ComponentRef<typeof PFTextArea>, TextAreaProps>(
  function TextArea(props, ref) {
    return <PFTextArea ref={ref} {...props} />;
  },
);
