/**
 * DS TextInput — PatternFly 6 TextInput under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Refs forward to PF6's TextInput (a forwardRef component).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { forwardRef } from "react";
import { TextInput as PFTextInput } from "@patternfly/react-core";
import type {
  ComponentPropsWithoutRef,
  ComponentRef,
  ForwardRefExoticComponent,
  RefAttributes,
} from "react";

export type TextInputProps = ComponentPropsWithoutRef<typeof PFTextInput>;

export const TextInput: ForwardRefExoticComponent<
  TextInputProps & RefAttributes<ComponentRef<typeof PFTextInput>>
> = forwardRef<ComponentRef<typeof PFTextInput>, TextInputProps>(
  function TextInput(props, ref) {
    return <PFTextInput ref={ref} {...props} />;
  },
);
