/**
 * DS Timestamp — PatternFly 6 Timestamp under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref: PF6's Timestamp is a plain function component (nothing to forward).
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Timestamp as PFTimestamp } from "@patternfly/react-core";
import type { ComponentPropsWithoutRef } from "react";

export type TimestampProps = ComponentPropsWithoutRef<typeof PFTimestamp>;

export function Timestamp(props: TimestampProps) {
  return <PFTimestamp {...props} />;
}

export {
  TimestampFormat,
  TimestampTooltipVariant,
} from "@patternfly/react-core";
