/**
 * DS Timestamp — PatternFly 6 Timestamp under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Timestamp as PFTimestamp } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TimestampProps = Omit<ComponentProps<typeof PFTimestamp>, "ref">;

export function Timestamp(props: TimestampProps) {
  return <PFTimestamp {...props} />;
}

export {
  TimestampFormat,
  TimestampTooltipVariant,
} from "@patternfly/react-core";
