/**
 * DS TimePicker — PatternFly 6 TimePicker under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { TimePicker as PFTimePicker } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TimePickerProps = Omit<ComponentProps<typeof PFTimePicker>, "ref">;

export function TimePicker(props: TimePickerProps) {
  return <PFTimePicker {...props} />;
}
