/**
 * DS Title — PatternFly 6 Title under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Title as PFTitle } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TitleProps = Omit<ComponentProps<typeof PFTitle>, "ref">;

export function Title(props: TitleProps) {
  return <PFTitle {...props} />;
}
