/**
 * DS ToggleGroup — PatternFly 6 ToggleGroup under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { ToggleGroup as PFToggleGroup } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ToggleGroupProps = Omit<ComponentProps<typeof PFToggleGroup>, "ref">;

export function ToggleGroup(props: ToggleGroupProps) {
  return <PFToggleGroup {...props} />;
}

export {
  ToggleGroupItem,
} from "@patternfly/react-core";
