/**
 * DS Tooltip — PatternFly 6 Tooltip under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Tooltip as PFTooltip } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TooltipProps = Omit<ComponentProps<typeof PFTooltip>, "ref">;

export function Tooltip(props: TooltipProps) {
  return <PFTooltip {...props} />;
}
