/**
 * DS Toolbar — PatternFly 6 Toolbar under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Toolbar as PFToolbar } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type ToolbarProps = Omit<ComponentProps<typeof PFToolbar>, "ref">;

export function Toolbar(props: ToolbarProps) {
  return <PFToolbar {...props} />;
}

export {
  ToolbarContent,
  ToolbarFilter,
  ToolbarGroup,
  ToolbarItem,
} from "@patternfly/react-core";
