/**
 * DS Toolbar — PatternFly 6 Toolbar under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * No ref forwarded: PF6's Toolbar is a class component — its ref is the class instance, not a DOM node. Use PF's innerRef-style props where provided.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Toolbar as PFToolbar } from "@patternfly/react-core";
import type { ToolbarProps as PFToolbarProps } from "@patternfly/react-core";

export type ToolbarProps = Omit<PFToolbarProps, "ref">;

export function Toolbar(props: ToolbarProps) {
  return <PFToolbar {...props} />;
}

export {
  ToolbarContent,
  ToolbarFilter,
  ToolbarGroup,
  ToolbarItem,
} from "@patternfly/react-core";
