/**
 * DS Truncate — PatternFly 6 Truncate under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Truncate as PFTruncate } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type TruncateProps = Omit<ComponentProps<typeof PFTruncate>, "ref">;

export function Truncate(props: TruncateProps) {
  return <PFTruncate {...props} />;
}

export {
  TruncatePosition,
} from "@patternfly/react-core";
