/**
 * DS Wizard — PatternFly 6 Wizard under the Golden Passport dials.
 * Thin wrapper: the dial CSS (src/styles) already brands it; add DS
 * defaults here when the design system diverges from stock PF6.
 * Generated by scripts/gen-pf-wrappers.mjs — hand-maintained after that.
 */
import { Wizard as PFWizard } from "@patternfly/react-core";
import type { ComponentProps } from "react";

export type WizardProps = Omit<ComponentProps<typeof PFWizard>, "ref">;

export function Wizard(props: WizardProps) {
  return <PFWizard {...props} />;
}

export {
  WizardStep,
} from "@patternfly/react-core";

export type {
  WizardStepType,
} from "@patternfly/react-core";
